### ISSUE TITLE
We have files in the repo that probably shouldn't be there

### ISSUE THREAD

**Issue by JGelfand** [FRCTeam159/2017-Robot-Code#2]
build.xml and laguage.settings.xml, and stuff from the debug folder for multiple libraries. This is stuff that causes a lot of rather pointless conflicts, and quite frankly is generated by Eclipse and therefore not necessary to have in the repo. We should remove these before they end up causing us some grief when we try to merge a project that we built on a different computer from the one these commits came from.

**Comment by Alpine-Robotics** [comment]
I just added a top level .gitignore file that includes ".settings/" etc. which (hopefully) should prevent those files and directories from being accidentally checked in in the future. Unfortunately, I'm not 100% sure what Eclipse files are important to archive and which ones caused us problems in the past

**Comment by JGelfand** [comment]
Seems to be fixed now.

**Comment by Alpine-Robotics** [comment]
Here's a link I found to remove the tracking of files already checked into git:
http://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by JGelfand** [comment]
First, I thought we had already removed all of those files- If you look at the repo, you'll notice that none of them are in there. Second, could you please use your personal account? It'll be hard to have a proper conversation if everyone is using the organizational one.

**Comment by dwsindorf** [comment]
The link I provided was just FYI, so nothing to get excited about

**Comment by dwsindorf** [comment]
(Re)closing this issue (nuf' said)

**Comment by JGelfand** [comment]
Gotcha- Sorry about that, I was sorta worried that we'd missed a file XD.

**Comment by dwsindorf** [comment]
We had serious problems today in trying to deploy "DiscusBot" to the Roborio from Eclipse (on the black computer). It seemed to keep trying to deploy "Shawntelle", even if the "DiscusBot" project was selected in the project explorer. If all other projects except DiscusBot were closed "run as WPILIB C++ Deploy" didn't do anything.
I'm wondering now if we are archiving the correct Eclipse project files (???)
