### ISSUE TITLE
Deploy issues w/DiscusBot

### ISSUE THREAD

**Issue by JGelfand** [FRCTeam159/2017-Robot-Code#8]
(from [Dean's comment](https://github.com/FRCTeam159/2017-Robot-Code/issues/2#issuecomment-251853825)):

> We had serious problems today in trying to deploy "DiscusBot" to the Roborio from Eclipse (on the black computer). It seemed to keep trying to deploy "Shawntelle", even if the "DiscusBot" project was selected in the project explorer. If all other projects except DiscusBot were closed "run as WPILIB C++ Deploy" didn't do anything.
> I'm wondering now if we are archiving the correct Eclipse project files (???)

It looks like both Shawtelle and discus have a .cproject, .project, and build.properties file. Discusbot actually has an additional .gitignore that Shawntelle doesn't but other than that they have the same files. If Shawntelle is deploying and DiscusBot isn't, it might be 
1. The contents of one of the files, or
2. Some setting in Eclipse itself

**Comment by dwsindorf** [comment]
Eclipse was also acting crazy on the silver computer. About every 10 minutes or so it would seem to forget that the project selected in the "project Explorer" tree was a "WPI Deploy" project and the only run choice was "Local/C++ Application". After this happened the only thing that restored the correct behaviour was to close and reopen Eclipse (I remember that this was a big problem a couple of years ago but don't remember encountering it last season)

**Comment by JGelfand** [comment]
I think we sometimes managed to fix that by closing and reopening the c/c++ perspective.

**Comment by JGelfand** [comment]
These appear to have been fixed.
